import type { Metadata } from "next";
import "./globals.css";
import Appbar from "@/components/Appbar";
import localFont from "next/font/local";

const generalSans = localFont({
  src: [
    {
      path: "../assets/fonts/GeneralSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-generalSans",
});

export const metadata: Metadata = {
  title: "Athwee | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} font-generalSans antialiased`}>
        <Appbar />
        {children}
      </body>
    </html>
  );
}
