import type { Metadata } from "next";
import "./globals.css";
import { Saira } from "next/font/google";
import localFont from "next/font/local";

export const saira = Saira({
  subsets: ["latin"],
  variable: "--font-saira",
});

const generalSans = localFont({
  src: [
    {
      path: "../assets/fonts/GeneralSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/GeneralSans-Bold.otf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../assets/fonts/GeneralSans-Light.otf",
      weight: "300",
      style: "light",
    },
    {
      path: "../assets/fonts/GeneralSans-Semibold.otf",
      weight: "500",
      style: "semibold",
    },
    {
      path: "../assets/fonts/GeneralSans-Medium.otf",
      weight: "600",
      style: "medium",
    },
  ],
  variable: "--font-generalSans",
});

export const metadata: Metadata = {
  title: "Athwee | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} font-generalSans antialiased`}>
        {children}
      </body>
    </html>
  );
}
